name: Model Evaluation

on:
  workflow_run:
    workflows: ["Run Tests and Lint"] 
    types:
      - completed

jobs:
  evaluate:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Model Evaluation
        run: |
          python tests/evaluation/evaluate_model.py 

      - name: Upload Evaluation Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: evaluation-artifacts
          path: output/model_output/evaluation/

      - name: Check Performance Threshold
        run: |
          # Extract accuracy from metrics.txt
          ACCURACY=$(grep "Validation Accuracy" output/model_output/evaluation/metrics.txt | awk '{print $NF}')
          echo "Model Accuracy: $ACCURACY"
          
          # Set a threshold of 0.50 (50% accuracy)
          if (( $(echo "$ACCURACY < 0.50" | bc -l) )); then
            echo "Model accuracy is below threshold. Failing the workflow."
            exit 1
          fi
