name: Run Tests and Lint

on:
  push:
  pull_request:

jobs:
  build:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pylint black

      - name: Run Unit Tests
        run: |
          export PYTHONPATH=.
          pytest --disable-warnings -v --cov tests/

      - name: Run Code Quality Checks
        run: |
          export PYTHONPATH=.
          MODIFIED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^src/' || true)
          
          if [ -n "$MODIFIED_FILES" ]; then
            black --check $MODIFIED_FILES
            pylint $MODIFIED_FILES
          else
            echo "No modified files to check."
          fi

          # The following flake8 step is commented out to prevent style errors from failing the workflow:
          # flake8 src/ --ignore=E501,E203,W503