name: Run Tests and Lint

on:
  push:
  pull_request:

jobs:
  build:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pylint black

      - name: Cache Hugging Face Models
        uses: actions/cache@v3
        with:
          path: ~/.cache/huggingface
          key: huggingface-${{ runner.os }}-bert-base-uncased
          restore-keys: |
            huggingface-${{ runner.os }}-

      - name: Preload Model
        run: |
          python -c "from transformers import AutoModel, AutoTokenizer; \
                     AutoModel.from_pretrained('bert-base-uncased'); \
                     AutoTokenizer.from_pretrained('bert-base-uncased')"

      - name: Run Unit Tests
        run: |
          export PYTHONPATH=.
          pytest --disable-warnings -v --cov tests/

      - name: Run Black (Code Formatting Check)
        run: |
          export PYTHONPATH=.
          black --check src/

      - name: Run Pylint (Code Quality Check)
        run: |
          export PYTHONPATH=.
          pylint src/

      - name: Run Flake8 (Code Style Check)
        run: |
          export PYTHONPATH=.
          flake8 src/ --ignore=E501,E203,W503
